export const SET_COURSES_VIEW_TYPE = "SET_COURSES_VIEW_TYPE";

export const GET_COURSE_CARD_REQUEST = "GET_COURSE_CARD_REQUEST";
export const GET_COURSE_CARD_SUCCESS = "GET_COURSE_CARD_SUCCESS";
export const GET_COURSE_CARD_FAILURE = "GET_COURSE_CARD_FAILURE";



export const GET_COURSE_DETAILS_BY_ID_REQUEST =
  "GET_COURSE_DETAILS_BY_ID_REQUEST";
export const GET_COURSE_DETAILS_BY_ID_SUCCESS =
  "GET_COURSE_DETAILS_BY_ID_SUCCESS";
export const GET_COURSE_DETAILS_BY_ID_FAILURE =
  "GET_COURSE_DETAILS_BY_ID_FAILURE";


  export const GET_CART_LIST_REQUEST = "GET_CART_LIST_REQUEST";
  export const GET_CART_LIST_SUCCESS = "GET_CART_LIST_SUCCESS";
  export const GET_CART_LIST_FAILURE = "GET_CART_LIST_FAILURE";


  export const LINK_PRODUCT_INFO_REQUEST =
  "LINK_PRODUCT_INFO_REQUEST";
export const LINK_PRODUCT_INFO_SUCCESS =
  "LINK_PRODUCT_INFO_SUCCESS";
export const LINK_PRODUCT_INFO_FAILURE =
  "LINK_PRODUCT_INFO_FAILURE";


  export const UPDATE_CART_REQUEST =
"UPDATE_CART_REQUEST";
export const UPDATE_CART_SUCCESS =
"UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAILURE =
"UPDATE_CART_FAILURE";